apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: goorm-task2-mysql
  namespace: goorm
  labels:
    app: goorm-task2
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: goorm-hard
  resources:
    requests:
      storage: 20Gi